### ISSUE TITLE
CURL /v1/docker-flow-swarm-listener/get-nodes return 404

### ISSUE THREAD

**Issue by jaschaio** [docker-flow/docker-flow-swarm-listener#3] opened 2018-04-27 06:32 UTC
I have set up docker swarm listener like this:

```
    swarm-listener:
        image: dockerflow/docker-flow-swarm-listener:18.04.15-5
        networks:
            - proxy
            - monitor
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DF_NOTIFY_CREATE_SERVICE_URL=http://letsencrypt:8080/v1/docker-flow-proxy-letsencrypt/reconfigure,http://monitor:8080/v1/docker-flow-monitor/reconfigure
            - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove,http://monitor:8080/v1/docker-flow-monitor/remove
            - DF_NOTIFY_CREATE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/reconfigure
            - DF_NOTIFY_REMOVE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/remove
            - DF_INCLUDE_NODE_IP_INFO=true
            - DF_RETRY_INTERVAL=5
        deploy:
            placement:
                constraints:
                    - node.role == manager
```

If I deploy it like this the health check seems to fail each time (`task: non-zero exit (2): dockerexec: unhealthy container`) and restarts another container.

If I try to `curl` the `/v1/docker-flow-swarm-listener/get-nodes` I get a 404 not found error.

Curling any other endpoint (for example `/v1/docker-flow-swarm-listener/get-services`) does work as expected.

I actually noticed that problem as I only get the internal service IPs within my `docker-flow-monitor` prometheus exporters.

If I remove the `DF_NOTIFY_CREATE_NODE_URL`, `DF_NOTIFY_REMOVE_NODE_URL` and `DF_INCLUDE_NODE_IP_INFO` the service works without problems. If I include any of them the healthcheck fails.

**Comment by jaschaio** [comment] 2018-04-27 09:53
I disabled the health check and were able to retrieve these logs:
```
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | panic: runtime error: invalid memory address or nil pointer dereference
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6e3006]
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | 
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | goroutine 101 [running]:
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | _/src/service.NotifyDistributor.processNodeNotification(0xc4202ee570, 0x808480, 0xc4202f0260, 0x808480, 0xc4202f0280, 0xc4202b46e0, 0x5, 0x809380, 0xc4204bdc00, 0x7c236e, ...)
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | 	/src/service/notifydistributor.go:232 +0x226
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | _/src/service.NotifyDistributor.distributeNodeNotification.func1(0xc4204de9e0, 0xc4202ee570, 0x808480, 0xc4202f0260, 0x808480, 0xc4202f0280, 0xc4202b46e0, 0x5, 0x809380, 0xc4204bdc00, ...)
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | 	/src/service/notifydistributor.go:203 +0xea
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | created by _/src/service.NotifyDistributor.distributeNodeNotification
infra_swarm-listener.1.0vjp0awimgqc@swarm-manager-03    | 	/src/service/notifydistributor.go:201 +0x234
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | goroutine 98 [running]:
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | _/src/service.NotifyDistributor.processNodeNotification(0xc4202ee570, 0x808480, 0xc4202f0260, 0x808480, 0xc4202f0280, 0xc4202b46e0, 0x5, 0x809380, 0xc4204d2940, 0x7c236e, ...)
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | 	/src/service/notifydistributor.go:232 +0x226
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | _/src/service.NotifyDistributor.distributeNodeNotification.func1(0xc4202d2a00, 0xc4202ee570, 0x808480, 0xc4202f0260, 0x808480, 0xc4202f0280, 0xc4202b46e0, 0x5, 0x809380, 0xc4204d2940, ...)
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | 	/src/service/notifydistributor.go:203 +0xea
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | created by _/src/service.NotifyDistributor.distributeNodeNotification
infra_swarm-listener.1.kswwoyse3oap@swarm-manager-01    | 	/src/service/notifydistributor.go:201 +0x234
```

**Comment by vfarcic** [comment] 2018-05-12 23:47
First of all, sorry for not responding earlier.

I think that there are two problems joined together. On one hand, DFSL does not handle the error well. It should present a useful error message, instead of Go stack trace. I can work on that during the next week.

The other, and more important problem, is that it fails to establish communication with `http://monitor:8080/v1/docker-flow-monitor/node/reconfigure`. Did you change the default path of DFM? It expects `http://monitor:8080/v1/docker-flow-monitor/reconfigure`, not `http://monitor:8080/v1/docker-flow-monitor/node/reconfigure`.

**Comment by dsw9742** [comment] 2018-05-13 12:03
Confirming we are also experiencing this issue when the environment variables `DF_NOTIFY_CREATE_NODE_URL` and `DF_NOTIFY_REMOVE_NODE_URL` are set. In our case, we are following the configuration details from http://monitor.dockerflow.com/config/#scrape-label-configuration-with-service-and-node-labels. I am thinking this is related to the flexible labels feature of DFM for node labels as opposed to service labels.

**Comment by thomasjpfan** [comment] 2018-05-14 17:47
Thanks @dsw9742 for pinging me about this. I'll look into what is going on.

**Comment by thomasjpfan** [comment] 2018-05-14 19:32
@vfarcic The stack trace comes from a previous version of DFSL. It is possible the issue is resolved with the new version.

@dsw9742 @jaschaio, Can you guys try out `dockerflow/docker-flow-swarm-listener:18.05.14-6` and see if it works for you?

**Comment by thomasjpfan** [comment] 2018-05-14 20:26
If there is another service that is failing to start up when DFSL is started up, DFSL fails to start up properly. I am looking into this now.

**Comment by dsw9742** [comment] 2018-05-14 20:48
I will check if 18.05.14-6 solves issue on my end tonight and report back here.

**Comment by dsw9742** [comment] 2018-05-15 00:07
No luck with the latest version either. Starts up just fine but then when the stack trace logs, DSFL fails and starts all over again (for me at least, we have restart policies in place). 

```
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | 2018/05/15 00:00:11 Starting Docker Flow: Swarm Listener
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | 2018/05/15 00:00:11 Sending notifications for running services and nodes
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | panic: runtime error: invalid memory address or nil pointer dereference
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7cc3f6]
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | 
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | goroutine 99 [running]:
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | _/src/service.NotifyDistributor.processNodeNotification(0xc4202f4630, 0x9525c0, 0xc420308200, 0x9525c0, 0xc420308220, 0xc4202c2690, 0x5, 0x953780, 0xc4201c99c0, 0x8fa85d, ...)
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | 	/src/service/notifydistributor.go:232 +0x226
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | _/src/service.NotifyDistributor.distributeNodeNotification.func1(0xc4204cd270, 0xc4202f4630, 0x9525c0, 0xc420308200, 0x9525c0, 0xc420308220, 0xc4202c2690, 0x5, 0x953780, 0xc4201c99c0, ...)
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | 	/src/service/notifydistributor.go:203 +0xea
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | created by _/src/service.NotifyDistributor.distributeNodeNotification
docker-flow-swarm-listener_core-infrastructure.1.wvwch2zwcjr9@swarm-manager-cd-1    | 	/src/service/notifydistributor.go:201 +0x234
docker-flow-swarm-listener_core-infrastructure.1.uhh6p95153sq@swarm-manager-cd-1    | 2018/05/15 00:00:48 Starting Docker Flow: Swarm Listener
docker-flow-swarm-listener_core-infrastructure.1.uhh6p95153sq@swarm-manager-cd-1    | 2018/05/15 00:00:48 Sending notifications for running services and nodes
```

**Comment by thomasjpfan** [comment] 2018-05-15 03:09
@dsw9742 `dockerflow/docker-flow-swarm-listener:18.05.15-7` should fix the stack trace issue. Please see if it works for you.

**Comment by dsw9742** [comment] 2018-05-15 10:08
@thomasjpfan confirming that the stack trace issue is resolved for us in 18.05.15-7. However, we are not yet seeing the node labels passed in the node created notifications:
```
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:39:01 Starting Docker Flow: Swarm Listener
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:39:01 Sending notifications for running services and nodes
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:40:02 Sending node created notification to http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.103&availability=active&hostname=generic-worker-prod-2&id=youi0ej7wu9rr6ouvwcdx12bg&role=worker&state=ready&versionIndex=106
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:40:02 Sending node created notification to http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.100&availability=active&hostname=swarm-manager-prod-1&id=nlzilhh0qwbpovlp8ot7ysil6&role=manager&state=ready&versionIndex=106
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:40:02 Sending node created notification to http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.105&availability=active&hostname=kafka-broker-prod-1&id=6yr4p63ch5tq84doaaqxy7ewx&role=worker&state=ready&versionIndex=106
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:40:02 Sending node created notification to http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.104&availability=active&hostname=zookeeper-prod-1&id=rne3r21wdckhee1z0whsrsbb4&role=worker&state=ready&versionIndex=106
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:40:02 Sending node created notification to http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.102&availability=active&hostname=generic-worker-prod-1&id=yrpznqtnr08ivbhfroy13t19y&role=worker&state=ready&versionIndex=106
docker-flow-swarm-listener_core-infrastructure.1.rdumfsos3xz8@swarm-manager-prod-1    | 2018/05/15 09:40:02 Sending node created notification to http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.101&availability=active&hostname=load-balancer-prod-1&id=rpaa1x3vh08rb7xhultupqgqi&role=worker&state=ready&versionIndex=106
```

**Comment by thomasjpfan** [comment] 2018-05-15 11:57
@dsw9742 Can you provide an example of your stack file?

**Comment by dsw9742** [comment] 2018-05-15 12:17
@thomasjpfan unfortunately we are not using stack files, but I might be able to copy/paste some of the CLI commands that are involved. Would that work?

**Comment by thomasjpfan** [comment] 2018-05-15 12:43
@dsw9742 Yes, cli commands would work.

**Comment by dsw9742** [comment] 2018-05-15 12:49
OK, I will pull something together for you today.

**Comment by thomasjpfan** [comment] 2018-05-15 18:51
`dockerflow/docker-flow-swarm-listener:18.05.15-11` should fix the failing Healthcheck issue.

I am unable to reproduce the missing node labels issue. Hopefully @dsw9742's cli commands can shed some light on this issue.

**Comment by dsw9742** [comment] 2018-05-15 20:09
@thomasjpfan I haven't forgotten about this, taking some time to get this to you. Thank you for continuing to work on this.

**Comment by dsw9742** [comment] 2018-05-15 21:03
@thomasjpfan try this : 

I tested this using Docker 18.03.1-ce and Ubuntu 18.04. I believe Docker Machine is v0.14 and Virtualbox is 5.2+.

Make sure to add an entry in your `/etc/hosts` file with IP address of the VM started by Docker Machine and pointed at `test.dfm.com`.

Running the below, then opening a browser locally and hitting test.dfm.com/targets does not show the node labels we expect to see.

```
#!/bin/bash

set -e

machine_name="test-swarm-manager-prod-1"

docker-machine create --driver virtualbox --virtualbox-memory 1024 --virtualbox-disk-size 10000 --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.03.1-ce/boot2docker.iso "${machine_name}"

docker-machine ssh "${machine_name}" "docker swarm init --advertise-addr $(docker-machine ip ${machine_name})"

docker-machine ssh "${machine_name}" "docker node update --label-add application=test-application --label-add swarm=production --label-add stack=core-infrastructure --label-add cloud=virtualbox --label-add region=us-east-1 --label-add zone=us-east-1a --label-add purpose=swarm-manager ${machine_name}"

docker-machine ssh "${machine_name}" "docker network create --driver overlay docker-flow-swarm-listener_core-infrastructure"
docker-machine ssh "${machine_name}" "docker network create --driver overlay docker-flow-monitor_core-infrastructure"
docker-machine ssh "${machine_name}" "docker network create --driver overlay load-balancer_core-infrastructure"

docker-machine ssh "${machine_name}" "docker service create \
              --name=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --no-healthcheck \
              --constraint 'node.role==manager' \
              --constraint \"node.labels.application==test-application\" \
              --constraint \"node.labels.swarm==production\" \
              --constraint \"node.labels.stack==core-infrastructure\" \
              --mode=replicated \
              --replicas=1 \
              --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
              --restart-condition=on-failure \
              --rollback-failure-action=pause \
              --rollback-parallelism=1 \
              --rollback-delay=0s \
              --update-failure-action=rollback \
              --update-parallelism=1 \
              --update-delay=0s \
              --label com.df.application=test-application \
              --label com.df.stack=core-infrastructure \
              --label com.df.purpose=docker-flow-swarm-listener \
              --label com.df.notify=true \
              --label com.df.port=8080 \
              --label com.df.scrapeNetwork=docker-flow-swarm-listener_core-infrastructure \
              --label com.df.scrapePort=8080 \
              --label com.df.alertName.1=replicas_less_than_1 \
              --label com.df.alertIf.1=@replicas_less_than:1 \
              --label com.df.alertPersistent.1=true \
              --label com.df.alertName.2=replicas_more_than_1 \
              --label com.df.alertIf.2=@replicas_more_than:1 \
              --label com.df.alertPersistent.2=true \
              --env \"DF_INCLUDE_NODE_IP_INFO=true\" \
              --env \"DF_NOTIFY_CREATE_NODE_URL=http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure\" \
              --env \"DF_NOTIFY_REMOVE_NODE_URL=http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/remove\" \
              --env \"DF_NOTIFY_CREATE_SERVICE_URL=http://load-balancer_core-infrastructure:8080/v1/docker-flow-proxy/reconfigure,http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/reconfigure\" \
              --env \"DF_NOTIFY_REMOVE_SERVICE_URL=http://load-balancer_core-infrastructure:8080/v1/docker-flow-proxy/remove,http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/remove\" \
              --detach=false \
                dockerflow/docker-flow-swarm-listener:18.05.15-7"

docker-machine ssh "${machine_name}" "docker service create \
              --name=docker-flow-monitor_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-monitor_core-infrastructure \
              --network=load-balancer_core-infrastructure \
              --constraint \"node.labels.application==test-application\" \
              --constraint \"node.labels.swarm==production\" \
              --constraint \"node.labels.stack==core-infrastructure\" \
              --mode=replicated \
              --replicas=1 \
              --mount type=volume,source=prometheus_data,destination=/prometheus \
              --restart-condition=on-failure \
              --rollback-failure-action=pause \
              --rollback-parallelism=1 \
              --rollback-delay=0s \
              --update-failure-action=rollback \
              --update-parallelism=1 \
              --update-delay=0s \
              --label com.df.application=test-application \
              --label com.df.stack=core-infrastructure \
              --label com.df.purpose=docker-flow-monitor \
              --label com.df.distribute=true \
              --label com.df.notify=true \
              --label com.df.port=9090 \
              --label com.df.scrapeNetwork=docker-flow-monitor_core-infrastructure \
              --label com.df.scrapePort=9090 \
              --label com.df.serviceDomain=test.dfm.com \
              --label com.df.srcPort=80 \
              --label com.df.alertName.1=replicas_less_than_1 \
              --label com.df.alertIf.1=@replicas_less_than:1 \
              --label com.df.alertPersistent.1=true \
              --label com.df.alertName.2=replicas_more_than_1 \
              --label com.df.alertIf.2=@replicas_more_than:1 \
              --label com.df.alertPersistent.2=true \
              --env \"ARG_STORAGE_TSDB_PATH=/prometheus\" \
              --env \"LISTENER_ADDRESS=docker-flow-swarm-listener\" \
              --env \"GLOBAL_SCRAPE_INTERVAL=10s\" \
              --env \"DF_GET_NODES_URL=http://docker-flow-swarm-listener_core-infrastructure:8080/v1/docker-flow-swarm-listener/get-nodes\" \
              --env \"DF_NODE_TARGET_LABELS=cloud,region,zone\" \
              --env \"DF_SCRAPE_TARGET_LABELS=application,stack,purpose\" \
              --detach=false \
                vfarcic/docker-flow-monitor:2-18.04.02-1"

docker-machine ssh "${machine_name}" "docker service create \
              --name=load-balancer_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-monitor_core-infrastructure \
              --network=load-balancer_core-infrastructure \
              --dns-option=timeout:1 \
              --publish mode=host,target=80,published=80 \
              --publish mode=host,target=443,published=443 \
              --constraint \"node.labels.application==test-application\" \
              --constraint \"node.labels.swarm==production\" \
              --constraint \"node.labels.stack==core-infrastructure\" \
              --mode=global \
              --mount type=volume,source=dfp-certs,destination=/certs \
              --restart-condition=on-failure \
              --rollback-failure-action=pause \
              --rollback-parallelism=1 \
              --rollback-delay=5s \
              --update-failure-action=rollback \
              --update-parallelism=1 \
              --update-delay=5s \
              --label com.df.application=test-application \
              --label com.df.stack=core-infrastructure \
              --label com.df.purpose=load-balancer \
              --label com.df.distribute=true \
              --label com.df.notify=true \
              --label com.df.scrapeNetwork=load-balancer_core-infrastructure \
              --label com.df.scrapePort=8080 \
              --env \"COMPRESSION_ALGO=gzip\" \
              --env \"CONNECTION_MODE=http-server-close\" \
              --env \"HEALTHCHECK=false\" \
              --env \"LISTENER_ADDRESS=docker-flow-swarm-listener_core-infrastructure\" \
              --env \"SERVICE_NAME=load-balancer_core-infrastructure\" \
              --env \"STATS_USER=none\" \
              --env \"STATS_PASS=none\" \
              --env \"STATS_PORT=80\" \
              --detach=false \
                dockerflow/docker-flow-proxy:18.05.08-46"
```

**Comment by thomasjpfan** [comment] 2018-05-15 23:54
I edited your example with the following changes:

1. Currently, DFSL only considers node labels prefixed by `com.df.`
2. I removed the scraping prometheus itself. I do not believe it has any metrics to scrape.
3. To use `replicas_less_than_1`, `google/cadvisor` needs to be created.

```bash
#!/bin/bash

set -e

machine_name="test-swarm-manager-prod-1"

docker-machine create --driver virtualbox --virtualbox-memory 1024 --virtualbox-disk-size 10000 --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.03.1-ce/boot2docker.iso "${machine_name}"

docker-machine ssh "${machine_name}" "docker swarm init --advertise-addr $(docker-machine ip ${machine_name})"

docker-machine ssh "${machine_name}" "docker node update --label-add com.df.application=test-application --label-add com.df.swarm=production --label-add com.df.stack=core-infrastructure --label-add com.df.cloud=virtualbox --label-add com.df.region=us-east-1 --label-add com.df.zone=us-east-1a --label-add com.df.purpose=swarm-manager ${machine_name}"

docker-machine ssh "${machine_name}" "docker network create --driver overlay docker-flow-swarm-listener_core-infrastructure"
docker-machine ssh "${machine_name}" "docker network create --driver overlay docker-flow-monitor_core-infrastructure"
docker-machine ssh "${machine_name}" "docker network create --driver overlay load-balancer_core-infrastructure"

docker-machine ssh "${machine_name}" "docker service create \
              --name=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --no-healthcheck \
              --constraint 'node.role==manager' \
              --constraint \"node.labels.com.df.application==test-application\" \
              --constraint \"node.labels.com.df.swarm==production\" \
              --constraint \"node.labels.com.df.stack==core-infrastructure\" \
              --mode=replicated \
              --replicas=1 \
              --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
              --restart-condition=on-failure \
              --rollback-failure-action=pause \
              --rollback-parallelism=1 \
              --rollback-delay=0s \
              --update-failure-action=rollback \
              --update-parallelism=1 \
              --update-delay=0s \
              --label com.df.application=test-application \
              --label com.df.stack=core-infrastructure \
              --label com.df.purpose=docker-flow-swarm-listener \
              --label com.df.notify=true \
              --label com.df.port=8080 \
              --label com.df.scrapeNetwork=docker-flow-swarm-listener_core-infrastructure \
              --label com.df.scrapePort=8080 \
              --label com.df.alertName.1=replicas_less_than_1 \
              --label com.df.alertIf.1=@replicas_less_than:1 \
              --label com.df.alertPersistent.1=true \
              --label com.df.alertName.2=replicas_more_than_1 \
              --label com.df.alertIf.2=@replicas_more_than:1 \
              --label com.df.alertPersistent.2=true \
              --env \"DF_INCLUDE_NODE_IP_INFO=true\" \
              --env \"DF_NOTIFY_CREATE_NODE_URL=http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/reconfigure\" \
              --env \"DF_NOTIFY_REMOVE_NODE_URL=http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/node/remove\" \
              --env \"DF_NOTIFY_CREATE_SERVICE_URL=http://load-balancer_core-infrastructure:8080/v1/docker-flow-proxy/reconfigure,http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/reconfigure\" \
              --env \"DF_NOTIFY_REMOVE_SERVICE_URL=http://load-balancer_core-infrastructure:8080/v1/docker-flow-proxy/remove,http://docker-flow-monitor_core-infrastructure:8080/v1/docker-flow-monitor/remove\" \
              --detach=false \
                dockerflow/docker-flow-swarm-listener:18.05.15-11"

docker-machine ssh "${machine_name}" "docker service create \
              --name=docker-flow-monitor_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-monitor_core-infrastructure \
              --network=load-balancer_core-infrastructure \
              --constraint \"node.labels.com.df.application==test-application\" \
              --constraint \"node.labels.com.df.swarm==production\" \
              --constraint \"node.labels.com.df.stack==core-infrastructure\" \
              --mode=replicated \
              --replicas=1 \
              --mount type=volume,source=prometheus_data,destination=/prometheus \
              --restart-condition=on-failure \
              --rollback-failure-action=pause \
              --rollback-parallelism=1 \
              --rollback-delay=0s \
              --update-failure-action=rollback \
              --update-parallelism=1 \
              --update-delay=0s \
              --label com.df.application=test-application \
              --label com.df.stack=core-infrastructure \
              --label com.df.purpose=docker-flow-monitor \
              --label com.df.distribute=true \
              --label com.df.notify=true \
              --label com.df.port=9090 \
              --label com.df.serviceDomain=test.dfm.com \
              --label com.df.srcPort=80 \
              --label com.df.alertName.1=replicas_less_than_1 \
              --label com.df.alertIf.1=@replicas_less_than:1 \
              --label com.df.alertPersistent.1=true \
              --label com.df.alertName.2=replicas_more_than_1 \
              --label com.df.alertIf.2=@replicas_more_than:1 \
              --label com.df.alertPersistent.2=true \
              --env \"ARG_STORAGE_TSDB_PATH=/prometheus\" \
              --env \"LISTENER_ADDRESS=docker-flow-swarm-listener_core-infrastructure\" \
              --env \"GLOBAL_SCRAPE_INTERVAL=10s\" \
              --env \"DF_GET_NODES_URL=http://docker-flow-swarm-listener_core-infrastructure:8080/v1/docker-flow-swarm-listener/get-nodes\" \
              --env \"DF_NODE_TARGET_LABELS=cloud,region,zone\" \
              --env \"DF_SCRAPE_TARGET_LABELS=application,stack,purpose\" \
              --detach=false \
                vfarcic/docker-flow-monitor:2-18.04.02-1"

docker-machine ssh "${machine_name}" "docker service create \
              --name=load-balancer_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-monitor_core-infrastructure \
              --network=load-balancer_core-infrastructure \
              --dns-option=timeout:1 \
              --publish mode=host,target=80,published=80 \
              --publish mode=host,target=443,published=443 \
              --constraint \"node.labels.com.df.application==test-application\" \
              --constraint \"node.labels.com.df.swarm==production\" \
              --constraint \"node.labels.com.df.stack==core-infrastructure\" \
              --mode=global \
              --mount type=volume,source=dfp-certs,destination=/certs \
              --restart-condition=on-failure \
              --rollback-failure-action=pause \
              --rollback-parallelism=1 \
              --rollback-delay=5s \
              --update-failure-action=rollback \
              --update-parallelism=1 \
              --update-delay=5s \
              --label com.df.application=test-application \
              --label com.df.stack=core-infrastructure \
              --label com.df.purpose=load-balancer \
              --label com.df.distribute=true \
              --label com.df.notify=true \
              --label com.df.scrapeNetwork=load-balancer_core-infrastructure \
              --label com.df.scrapePort=8080 \
              --env \"COMPRESSION_ALGO=gzip\" \
              --env \"CONNECTION_MODE=http-server-close\" \
              --env \"HEALTHCHECK=false\" \
              --env \"LISTENER_ADDRESS=docker-flow-swarm-listener_core-infrastructure\" \
              --env \"SERVICE_NAME=load-balancer_core-infrastructure\" \
              --env \"STATS_USER=none\" \
              --env \"STATS_PASS=none\" \
              --env \"STATS_PORT=80\" \
              --detach=false \
                dockerflow/docker-flow-proxy:18.05.08-46"

docker-machine ssh "${machine_name}" "docker service create \
              --name=cadvisor_core-infrastructure \
              --network=docker-flow-swarm-listener_core-infrastructure \
              --network=docker-flow-monitor_core-infrastructure \
              --constraint \"node.labels.com.df.application==test-application\" \
              --constraint \"node.labels.com.df.swarm==production\" \
              --constraint \"node.labels.com.df.stack==core-infrastructure\" \
              --mode=global \
              --label com.df.notify=true \
              --label com.df.scrapePort=8080 \
              --label com.df.scrapeNetwork=docker-flow-monitor_core-infrastructure \
              --label com.df.application=system \
              --mount type=bind,source=/,destination=/rootfs \
              --mount type=bind,source=/var/run,destination=/var/run \
              --mount type=bind,source=/sys,destination=/sys \
              --mount type=bind,source=/var/lib/docker,destination=/var/lib/docker \
              --detach=false \
              google/cadvisor:v0.29.0"
```

**Comment by dsw9742** [comment] 2018-05-16 10:44
@thomasjpfan I think this will work -- will also check this morning

**Comment by dsw9742** [comment] 2018-05-17 18:47
I believe this puts us on the right path :)

Thanks @thomasjpfan !

**Closed** 2018-06-02 15:07 UTC
